name: Build Application
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint:code:fix
      - name: Lint styles
        run: npm run lint:style:fix
  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
