name: Chek
on:
  push:
    branches:
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint:code
      - name: Lint styles
        run: npm run lint:style
